language: cpp
sudo: required
os:
    - linux

services:
    - docker
env:
  global:
    - CC_TEST_REPORTER_ID=2727af6b46213a350cb85449e8d3b538edcd7221168f668c940ef86f07718184
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

before_install:
    - docker pull jpakkane/mesonci:zesty

script:
  -  echo FROM jpakkane/mesonci:zesty > Dockerfile
  -  echo ADD . /root >> Dockerfile
  -  docker build -t withgit .
  -  docker run withgit bash -c "apt update && apt upgrade -qq -y"
  -  docker run withgit bash -c "curl -O http://download.opensuse.org/repositories/home:hpcoder1/xUbuntu_17.10/Release.key"
  -  docker run withgit bash -c "echo 'deb http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_17.10/ /' >/tmp/hpcoders.list "
  -  docker run withgit bash -c "mv /tmp/hpcoders.list /etc/apt/sources.list.d/"
  -  docker run withgit bash -c "apt-get update -qq"
  -  docker run withgit bash -c "apt-key add - < Release.key" 
  -  docker run withgit bash -c "apt-get install -y meson libxml2 libboost-dev json-spirit"
  -  docker run withgit /bin/sh -c "cd /root && TRAVIS=true CC=$CC CXX=$CXX meson builddir && ninja -C builddir"
  #- ninja -C builddir test

  
