language: cpp
sudo: true
services: docker
os: linux
env:
  global:
    - CC_TEST_REPORTER_ID=2727af6b46213a350cb85449e8d3b538edcd7221168f668c940ef86f07718184
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then brew install ninja python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then pip3 install meson; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"  ]]; then docker pull highperformancecoder/classdesc:yakkety; fi
  - wget http://download.opensuse.org/repositories/home:hpcoder1/xUbuntu_16.10/Release.key
  - sudo apt-key add - < Release.key
  - echo 'deb http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_16.10/ /' >/tmp/hpcoders.list 
  - sudo mv /tmp/hpcoders.list /etc/apt/sources.list.d/
  - sudo apt-get update -qq
  - sudo apt-get install -y json-spirit
  - sudo apt-get install -y libboost-dev
  - sudo apt-get install -y libxml2-utils
  - sudo apt-get install -y meson
  - sudo apt-get install -y ninja
script: 
  - if [[ "$TRAVIS_OS_NAME" == "linux"  ]]; then echo FROM highperformancecoder/classdesc:yakkety > Dockerfile; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"  ]]; then echo ADD . /root >> Dockerfile; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"  ]]; then docker build -t withgit .; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"  ]]; then docker run withgit /bin/sh -c "cd /root && TRAVIS=true CC=$CC CXX=$CXX meson builddir && ninja -C builddir test"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then SDKROOT=$(xcodebuild -version -sdk macosx Path) meson builddir && ninja -C builddir test; fi
